replicaCount: 3

image:
  repository: 334575333234.dkr.ecr.ap-south-1.amazonaws.com/manixil-app
  tag: "latest"
  pullPolicy: Always

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

tolerations:
  - key: "app"
    operator: "Equal"
    value: "manixil"
    effect: "NoSchedule"

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30000

containerPort: 3000
