replicaCount: 4

image:
  repository: 334575333234.dkr.ecr.ap-south-1.amazonaws.com/manixil-app
  tag: "latest"
  pullPolicy: Always

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

nodeSelector:
  app: manixil

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30000
  
containerPort: 3000
